spring:
  application:
    name: livrotech
  profiles:
    default: dev
  jpa:
    open-in-view: false
app:
  security:
    enabled: true
  seed-data:
    enabled: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n"