create table books (
    id bigint generated by default as identity,
    title varchar(150) not null,
    author varchar(100) not null,
    price numeric(12, 2) not null,
    version bigint,
    constraint pk_books primary key (id),
    constraint uk_book_title_author unique (title, author)
);

create table customers (
    id bigint generated by default as identity,
    name varchar(100) not null,
    cpf varchar(11) not null,
    status varchar(255) not null,
    version bigint,
    constraint pk_customers primary key (id),
    constraint uk_customers_cpf unique (cpf)
);

create table employees (
    id bigint generated by default as identity,
    name varchar(100) not null,
    cpf varchar(11) not null,
    registration_number integer not null,
    position varchar(80) not null,
    status varchar(255) not null,
    version bigint,
    constraint pk_employees primary key (id),
    constraint uk_employees_cpf unique (cpf),
    constraint uk_employees_registration_number unique (registration_number)
);

create table sales (
    id bigint generated by default as identity,
    customer_id bigint not null,
    employee_id bigint not null,
    book_id bigint not null,
    sale_date date not null,
    constraint pk_sales primary key (id),
    constraint fk_sales_customer foreign key (customer_id) references customers (id),
    constraint fk_sales_employee foreign key (employee_id) references employees (id),
    constraint fk_sales_book foreign key (book_id) references books (id)
);

create table customer_purchases (
    customer_id bigint not null,
    book_id bigint not null,
    constraint pk_customer_purchases primary key (customer_id, book_id),
    constraint fk_customer_purchases_customer foreign key (customer_id) references customers (id),
    constraint fk_customer_purchases_book foreign key (book_id) references books (id)
);
